### ISSUE TITLE
how we can proxy RestFul web service (Spring MVC) in WSO2 API manager

### ISSUE THREAD

**Issue by JavaHelper** [wso2/wso2-api-manager-plugins#2]
Do you know how we can proxy RestFul web service (Spring MVC) in WSO2 API manager? Could you please share step by step simple example?

**Comment by jranabahu** [comment]
Hi JavaHelper,

We appreciate your interest towards the WSO2 API Manager and we would like to point you towards our documentation where it describes how to use WSO2 API Manager. Please refer to [1] for more information.

Thanks,
Janaka

[1] https://docs.wso2.com/display/AM200/Create+and+Publish+an+API
